# Generated by Django 3.2.5 on 2021-07-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
