# Generated by Django 3.2.5 on 2021-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='highlite',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
