# Generated by Django 3.2.5 on 2021-07-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='highlite',
            new_name='highlight',
        ),
    ]
